server:
  port: 8761

# Nombre de mi app
spring:
  application:
    name: msvc-eureka
  config:
    import: optional:configserver:http://localhost:8888

# Servidor de Eureka
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-register: false
    server-url:
      defaultZone: http://localhost:${server.port}/eureka/

